[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=tiny_eva"
test_paths = [
    "tests",
]

[tool.mypy]
mypy_path = "tiny_eva"